version: '3.8'

services:
  web:
    build: .
    container_name: helpdesk_mattos
    restart: always
    ports:
      - "5001:5000"  # <--- AQUI: Porta 5001 externa -> 5000 interna
    volumes:
      - ./instance:/app/instance
    env_file:
      - .env