"""Criação inicial

Revision ID: 45b24ac75e76
Revises: 
Create Date: 2025-07-08 15:42:05.368804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b24ac75e76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['criador_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('respondente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['respondente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    op.drop_table('ticket')
    op.drop_table('user')
    op.drop_table('setor')
    op.drop_table('categoria')
    # ### end Alembic commands ###
